DU-Summer-2023-Capstone/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace DU_Summer_2023_Capstone.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            ViewData["Title"] = "Home";
            return View();
        }
    }
}

DU-Summer-2023-Capstone/Controllers/MenuController.cs
using DU_Summer_2023_Capstone.Data.Interfaces;
using DU_Summer_2023_Capstone.PagesModel;
using Microsoft.AspNetCore.Mvc;
namespace DU_Summer_2023_Capstone.Controllers
{
    public class MenuController : Controller
    {
        private readonly IPizzaRepository _pizzaRepository;
        public MenuController(IPizzaRepository pizzaRepository)
        {
            _pizzaRepository = pizzaRepository;
        }

        // GET: MenuController
        public ActionResult Index()
        {
            var homeViewModel = new MenuModel
            {
                Pizzas = _pizzaRepository.Pizzas
            };
            return View(homeViewModel);
        }

        // GET: MenuController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MenuController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MenuController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MenuController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MenuController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MenuController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

DU-Summer-2023-Capstone/Views/Home/Index.cshtml
@page
<!--Home Page Hero Banner-->
<section id="Index-Hero" class="container-fluid" style="background-image: url('/images/Hero-Pizza.jpeg'); margin: 0; padding: 0;">
    <div class="container-fluid d-flex justify-content-center align-items-center h-100 mask" style="background-color: rgba(0,0,0,.8); margin: 0; padding: 0;">
        <div class="row justify-content-center align-items-center" style="padding: 0; margin: 0;">
            <div class="col-auto text-center text-white">
                <h1 class="display-1 fw-bold"> Pizza Pete</h1>
                <h3 class=""><strong class="mt-3">All your favorite pizza from Pizza Pete</strong></h3>
                <a role="button" class="btn btn-primary mt-5" asp-controller="Menu" asp-action="Index">Shop Now</a>
            </div>
        </div>

        <img src="/images/Chef.png" style="position: absolute; bottom: 0; right: 0;" />
    </div>
</section>