DU-Summer-2023-Capstone/Controllers/CartController.cs
using DU_Summer_2023_Capstone.Data.Interfaces;
using DU_Summer_2023_Capstone.Data.Models;
using DU_Summer_2023_Capstone.PagesModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DU_Summer_2023_Capstone.Controllers
{
    public class CartController : Controller
    {
        private readonly IPizzaRepository _pizzaRepository;
        private readonly Cart _cart;

        public CartController(IPizzaRepository pizzaRepository, Cart cart)
        {
            _pizzaRepository = pizzaRepository;
            _cart = cart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;

            var cartViewModel = new CartViewModel
            {
                Cart = _cart,
                CartTotal = _cart.GetCartTotal()
            };
            return View(cartViewModel);
        }

        [Authorize]
        public ViewResult Checkout()
        {
            var items = _cart.GetCartItems();
            var cartViewModel = new CartViewModel
            {
                Cart = _cart,
                CartTotal = _cart.GetCartTotal()
            };
            if (items != null && items.Count > 0)
            {
                return View(cartViewModel);
            }
            else
            {
                return View("Index", cartViewModel);

            }

        }

        public ViewResult OrderDetails()
        {
            return View();
        }

        [Authorize]
        public RedirectToActionResult AddToCart(int pizzaId)
        {
            var selectedPizza = _pizzaRepository.Pizzas.FirstOrDefault(p => p.PizzaId == pizzaId);
            if (selectedPizza != null)
            {
                _cart.AddToCart(selectedPizza, 1);
            }
            return RedirectToAction("Index", "Menu");
        }

        [Authorize]
        public RedirectToActionResult IncreaseAmmount(int pizzaId)
        {
            var selectedPizza = _pizzaRepository.Pizzas.FirstOrDefault(p => p.PizzaId == pizzaId);
            if (selectedPizza != null)
            {
                _cart.AddToCart(selectedPizza, 1);
            }
            return RedirectToAction("Index");
        }
        public RedirectToActionResult RemoveFromCart(int pizzaId)
        {
            Console.WriteLine(pizzaId);


            var selectedPizza = _pizzaRepository.Pizzas.FirstOrDefault(p => p.PizzaId == pizzaId);

            if (selectedPizza != null)
            {
                _cart.RemoveFromCart(selectedPizza);
            }
            return RedirectToAction("Index");
        }




    }
}

DU-Summer-2023-Capstone/Controllers/PagesController.cs
using Microsoft.AspNetCore.Mvc;

namespace DU_Summer_2023_Capstone.Controllers
{
    public class PagesController : Controller
    {
        //Use controller methods to access & deliver data before the page loads to display on page
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Menu()
        {
            //ie: can search for current user & their most ordered products, then return all products ordered by most purchased
            return View();
        }

        public IActionResult Cart()
        {
            return View();
        }


        /*
        public IActionResult Checkout()
        {
            return View();
        }

        
        public IActionResult storeOrder()
        {
            //validate request
                //if not validated -> return back with errors

            //if validated
            
            //store the data

            //return order success page
        }
        */
    }
}

DU-Summer-2023-Capstone/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizza Pete</title>

    <!--Favicon-->
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico" />

    <!--CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <div>
                    <a class="navbar-brand" asp-area="" asp-controller="Pages" asp-action="Index"><img src="/images/Chef.png" width="50" height="50" style="margin-right: 10px;" /></a>
                        <a class="navbar-brand" asp-area="" asp-controller="Pages" asp-action="Index">Pizza Pete</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pages" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="View">Menu</a>
                        </li>
                    </ul>
                    <div class="d-flex flex-row">
                        <a class="nav-link text-dark d-flex" asp-controller="Cart" asp-action="View" style="margin: auto 0; font-size: 24px;"><i class="bi bi-cart3" style=""></i></a>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>